# Generated by Django 3.0 on 2020-05-26 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_auto_20200430_2312'),
        ('main', '0036_auto_20200417_1343'),
    ]

    operations = [
    ]
